### ISSUE TITLE
Allow installation of devel releases

### ISSUE THREAD

**Issue by aeons** [mracos/asdf-swiprolog#2]
It would be nice if you could install development releases as well as stable ones.

**Comment by mracos** [comment]
It would make sense on the `list-all` command if it also shows the development releases with a `-devel` appended to it?

Like:

- 7.6.4
- 7.7.9-devel

And then the install command would support installing from the development channel.

**Comment by aeons** [comment]
Sounds good!

**Comment by mracos** [comment]
Looking into it later today! :)

If you want to do it, just send a PR and I will be happy to merge it

**Comment by aeons** [comment]
Didn't have a chance to look at it, but 👍 that it's added :)
