### ISSUE TITLE
Fix testing in travis OSX

### ISSUE THREAD

**Issue by mracos** [mracos/asdf-swiprolog#9]
https://travis-ci.org/mracos/asdf-swiprolog/jobs/548463135

**Comment by neenjaw** [comment]
you need to install libarchive-dev on ubuntu and osx I think for it to build

**Comment by mracos** [comment]
Actually, I was already trying to install this package in both osx and linux.
But since the default travis OSX image is outdated, it was erroring out with `homebrew is outdated` error.

The solution quickest solution is to update the travis OSX image to the latest one.

Refs:
https://travis-ci.community/t/xcode-8-3-homebrew-outdated-error/3798
https://docs.travis-ci.com/user/reference/osx/#macos-version

**Comment by neenjaw** [comment]
Makes sense, I just saw it was failing at the same point as it was for me installing on Ubuntu/debian
